# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portfolio.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='제목')),
                ('location', models.CharField(max_length=50, verbose_name='장소')),
                ('work_period', models.CharField(max_length=50, verbose_name='공사기간')),
                ('description', models.TextField(blank=True, verbose_name='서두')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='게시일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='사진설명')),
                ('image', portfolio.fields.ThumbnailImageField(upload_to='photo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='게시일')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
            options={
                'ordering': ('create_date',),
            },
        ),
    ]
