# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('location', models.CharField(max_length=50, verbose_name='장소')),
                ('date', models.CharField(max_length=20, verbose_name='예상 공사시작 날짜')),
                ('image', portfolio.fields.ThumbnailImageField(upload_to='photo')),
                ('description', models.TextField(verbose_name='상세설명')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='휴대폰 번호')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='게시일')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
